spring.application.name=smart-campus-api
server.port=8080

spring.data.mongodb.uri=mongodb+srv://admin:12345@cluster0.irzzhre.mongodb.net/smart_campus_db?retryWrites=true&w=majority

app.jwt.secret=app.jwt.secret=app.jwt.secret=app.jwt.secret=SmartCampusSecretKeyForJwtSigningPurposeOnlyDoNotUseInProductionEnvironment2026!!
app.jwt.expiration-ms=86400000

spring.security.oauth2.client.registration.google.client-id=963988511076-r5g4djmac8lnkqbj8sk5p6qrm6canuuq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

app.frontend.url=http://localhost:5173

logging.level.com.smartcampus=DEBUG
logging.level.org.springframework.security=INFO